myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("showpage.urls")),
]

showpage/urls.py
from django.urls import path
from .views import *

app_name = "showpage"
urlpatterns = [
    path("", showmain, name="main"),  # 메인
    path("showstat_occ", showstat_occ, name="showstat_occ"),  # 직종별 통계
    path("showstat", showstat, name="showstat"),  # 지역별 통계
    path("regionjson", regionjson),  # json
    path("showmap", showmap, name="showmap"),  # 맞춤형
    path("showmapjson", showmapjson),  # 맞춤형 페이지 json
    path("showdetail/<int:ann_no>", showdetail),  # 공고 상세 페이지
    path("showkeyword", showkeyword, name="showkeyword"),  # 검색형 워드클라우드
    path("showkeywordjson", showkeywordjson),  # 워드클라우드 json
    path("showkeyword_occ", showkeyword_occ, name="showkeyword_occ"),  # 선택형 워드클라우드
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>{% block title %} {% endblock %}</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <!--<link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">-->
    <link rel="stylesheet" href="{% static  'assets/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel=" stylesheet" href=" {% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel=" stylesheet" href="{% static  'assets/vendor/boxicons/css/boxicons.min.css' %}">
    <link rel="stylesheet" href=" {% static  'assets/vendor/quill/quill.snow.css' %}">
    <link rel="stylesheet" href="{% static  'assets/vendor/quill/quill.bubble.css' %}">
    <link rel="stylesheet" href="{% static  'assets/vendor/remixicon/remixicon.css' %}">
    <link rel="stylesheet" href="{% static  'assets/vendor/simple-datatables/style.css' %}">

    <!-- Template Main CSS File -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %} ">
</head>

<body>

    <!-- 로딩창 -->
    <div id="loading_layer" style=" text-align: center; display: none;   
         z-index: 1;  position:absolute; height: 1700px; width: 100%; background-color: rgba(0,0,0,0.5);">

        <section class="loading" style="box-sizing: border-box; margin: 0 auto;">
            <h1 class="loading-title">Loading....</h1>
            <div class="progress-bar" aria-hidden="true">
                <span class="progress-bar-gauge"></span>
            </div>

    </div>
    {% include 'header.html' %}
    {% block content %}
    {% endblock %}
    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/chart.js/chart.min.js' %}"></script>
    <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/quill/quill.min.js' %}"></script>
    <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
    <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script src="{% static 'findheader.js' %}"></script>
    {% include 'footer.html' %}
    {% block script %}
    {% endblock %}
</body>

</html>

templates/footer.html
<footer id="footer" class="footer">
    <div class="copyright">
        &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
        Maded by <a href="https://www.notion.so/KDT_-2-5a9e813396f4476295ed417b05d160ff">ForSmartTechnology</a>
    </div>
</footer>
<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

templates/header.html
{% load static %}
<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a href="/" class="logo d-flex align-items-center">
            <img src="{% static 'assets/img/logo.png' %}" alt="">
            <span class="d-none d-lg-block">ForSB</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->
</header><!-- End Header -->

<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'showpage:main' %}">
                <i class="bi bi-grid"></i>
                <span>Main Screan</span>
            </a>
        </li><!-- End Dashboard(Main Screan) Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed  " data-bs-target="#stat" data-bs-toggle="collapse" href="#">
                <i class="bi bi-bar-chart"></i><span>통계정보</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="stat" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a id="/showstat" href="{% url 'showpage:showstat' %}" class="">
                        <i class="bi bi-circle"></i><span>지역별 현황</span>
                    </a>
                </li>
                <li>
                    <a id="/showstat_occ" href="{% url 'showpage:showstat_occ' %}">
                        <i class="bi bi-circle"></i><span>직종별 현황</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Charts(통계정보) Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#keyword" data-bs-toggle="collapse" href="#">
                <i class="bi bi-journal-text"></i><span>채용정보</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="keyword" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a id="/showkeyword" class="" href="{% url 'showpage:showkeyword' %}">
                        <!--Html 명 변경!!!-->
                        <i class="bi bi-circle"></i><span>채용정보 키워드</span>
                    </a>
                </li>
                <li>
                    <a id="/showkeyword_occ" href="{% url 'showpage:showkeyword_occ' %}">
                        <!--Html 명 변경!!!-->
                        <i class="bi bi-circle"></i><span>지역별 직종 키워드</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Forms(채용정보) Nav -->

        <!--===== <li class="nav-heading">Pages</li> =====-->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'showpage:showmap' %}">
                <!--Html 명 변경!!!-->
                <i class="bi bi-person"></i>
                <span>맞춤형 채용정보</span>
            </a>
        </li><!-- End Profile Page(맞춤형 채용정보) Nav -->

    </ul>
</aside><!-- End Sidebar-->